name: CI Pipeline - Testes da API

on:

  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ] 

jobs:
  build-and-test:
    # Define a máquina virtual para o job
    runs-on: ubuntu-latest

    # Define a sequência de passos
    steps:
      # 1. Baixa o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o ambiente Node.js
      - name: Configurar Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # 3. Instala as dependências do projeto
      - name: Instalar dependências
        run: npm ci

      # 4. Roda os testes
      - name: Rodar os testes
        run: npm test